In [1]:
# Importing Libraries
try:
    import pandas as pd
    import numpy as np
    from numpy import set_printoptions
    import os,sys
    import re
    # importing algorithms
    from sklearn.model_selection import train_test_split, RandomizedSearchCV, GridSearchCV
    from sklearn.linear_model import LogisticRegression
    from sklearn import svm
    from sklearn.metrics import confusion_matrix, classification_report
    from sklearn.preprocessing import Normalizer
    from sklearn.preprocessing import StandardScaler
except Exception as e:
    print("Error is due to",e)
pwd = os.getcwd()
labels_df = pd.read_csv(pwd+"//Datasets//Kabita//Input//kabita_dataset_labels.csv")

## Verloop BERT Sentence Transformer

In [28]:
# V BERT vectorized data
x_df = pd.read_csv(pwd+"//Datasets//Kabita//SentenceTransformers//bert_vectorized_kabita_dataset_vbert.csv")
y_df = labels_df['kabita_labels']
# Test train split
x_train,x_test,y_train,y_test = train_test_split(x_df, y_df, test_size=0.30,random_state=21,stratify=y_df)

# Normalize scaling of train data
normalize_model = Normalizer()
nscaled_data_train = normalize_model.fit_transform(x_train)
# Normalize scaling of test data
nscaled_data_test = normalize_model.fit_transform(x_test)

# Standard scaling of train data
standard_model = StandardScaler()
sscaled_data_train = standard_model.fit_transform(x_train)
# Standard scaling of test data
sscaled_data_test = standard_model.fit_transform(x_test)

### Hyperparameter Tuning for No Scaled Data for Logistic Regression

In [40]:
# Random Search CV

# Set up the sample space
c_list = [0.1, 1, 10, 100, 1000]
penalty_list=['l2']
max_iter_list = [1000,2000,3000,4000,5000,6000]
# Create the grid
parameter_grid = {'C' : c_list, 'penalty': penalty_list, 'max_iter': max_iter_list}
# Define how many samples
number_models = 10
# Create a random search object
random_LR_class = RandomizedSearchCV(estimator = LogisticRegression(),
                                      param_distributions = parameter_grid,
                                      n_iter = number_models,
                                      scoring='accuracy',
                                      n_jobs=6,
                                      cv = 5,
                                      refit=True,
                                      return_train_score = True)
# Fit the object to our data
random_LR_class.fit(x_train, y_train)

RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=6,
                   param_distributions={'C': [0.1, 1, 10, 100, 1000],
                                        'max_iter': [1000, 2000, 3000, 4000,
                                                     5000, 6000],
                                        'penalty': ['l2']},
                   return_train_score=True, scoring='accuracy')

In [41]:
# print best parameter after tuning
print(random_LR_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(random_LR_class.best_estimator_)

{'penalty': 'l2', 'max_iter': 5000, 'C': 1}
LogisticRegression(C=1, max_iter=5000)


In [42]:
# Predicted test outputs
random_LR_class_predictions = random_LR_class.predict(x_test)

#print Confusion Matrix
print(confusion_matrix(y_test,random_LR_class_predictions))
 
# print Classification Report
print(classification_report(y_test, random_LR_class_predictions))

[[164   2   0   3  32   8   1]
 [  1 171  10   8  11   8   1]
 [  0   1 196   6   1   6   0]
 [  3   6   4 166  15  14   2]
 [ 31  11   1  10 145   6   6]
 [  5  10   8  15   5 142  25]
 [  3   0   0   1   3  26 177]]
              precision    recall  f1-score   support

           1       0.79      0.78      0.79       210
           2       0.85      0.81      0.83       210
           3       0.89      0.93      0.91       210
           4       0.79      0.79      0.79       210
           5       0.68      0.69      0.69       210
           6       0.68      0.68      0.68       210
           7       0.83      0.84      0.84       210

    accuracy                           0.79      1470
   macro avg       0.79      0.79      0.79      1470
weighted avg       0.79      0.79      0.79      1470



In [43]:
# Examining results using pandas df
rand_cv_results_df = pd.DataFrame(random_LR_class.cv_results_)
pd.set_option('display.max_columns', None)
rand_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_penalty  \
0       5.412535      0.682226         0.022940        0.005359            l2   
1      24.905331      2.718335         0.021305        0.010119            l2   
2      12.199599      1.906480         0.018429        0.006444            l2   
3      11.993636      1.345737         0.026819        0.003537            l2   
4      39.789203      2.625781         0.020878        0.007559            l2   
5       5.975999      0.783036         0.017419        0.002163            l2   
6       6.077260      0.859855         0.025407        0.011448            l2   
7      21.698886      0.644300         0.023273        0.008580            l2   
8      61.211273      7.714237         0.019928        0.006020            l2   
9      48.964349      4.763919         0.013373        0.012049            l2   

  param_max_iter param_C                                          params  \
0           5000     0.1   {'penalty': 'l2', 'max_iter': 5000, 'C': 0.1}   
1           6000      10    {'penalty': 'l2', 'max_iter': 6000, 'C': 10}   
2           5000       1     {'penalty': 'l2', 'max_iter': 5000, 'C': 1}   
3           3000       1     {'penalty': 'l2', 'max_iter': 3000, 'C': 1}   
4           2000     100   {'penalty': 'l2', 'max_iter': 2000, 'C': 100}   
5           6000     0.1   {'penalty': 'l2', 'max_iter': 6000, 'C': 0.1}   
6           3000     0.1   {'penalty': 'l2', 'max_iter': 3000, 'C': 0.1}   
7           1000     100   {'penalty': 'l2', 'max_iter': 1000, 'C': 100}   
8           4000    1000  {'penalty': 'l2', 'max_iter': 4000, 'C': 1000}   
9           5000    1000  {'penalty': 'l2', 'max_iter': 5000, 'C': 1000}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.782799           0.763848           0.779883           0.763848   
1           0.744898           0.753644           0.747813           0.744898   
2           0.775510           0.769679           0.787172           0.776968   
3           0.775510           0.769679           0.787172           0.776968   
4           0.741983           0.758017           0.724490           0.734694   
5           0.782799           0.763848           0.779883           0.763848   
6           0.782799           0.763848           0.779883           0.763848   
7           0.739067           0.760933           0.724490           0.733236   
8           0.733236           0.749271           0.723032           0.723032   
9           0.733236           0.749271           0.723032           0.723032   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  \
0           0.759475         0.769971        0.009465                3   
1           0.755102         0.749271        0.004324                6   
2           0.769679         0.775802        0.006414                1   
3           0.769679         0.775802        0.006414                1   
4           0.740525         0.739942        0.010932                7   
5           0.759475         0.769971        0.009465                3   
6           0.759475         0.769971        0.009465                3   
7           0.741983         0.739942        0.012077                8   
8           0.733236         0.732362        0.009608                9   
9           0.733236         0.732362        0.009608                9   

   split0_train_score  split1_train_score  split2_train_score  \
0            0.856778            0.864796            0.855685   
1            0.996356            0.995991            0.997085   
2            0.960277            0.958819            0.960641   
3            0.960277            0.958819            0.960641   
4            0.997449            0.997085            0.998178   
5            0.856778            0.864796            0.855685   
6            0.856778            0.864796            0.855685   
7            0.997449            0.997085      

In [44]:
# Grid Search CV

# Set up the sample space
c_list = [0.1, 1, 2, 3]
penalty_list=['l2']
max_iter_list = [3000,4000,5000,6000]
# Create the grid
parameter_grid = {'C' : c_list, 'penalty': penalty_list, 'max_iter': max_iter_list}

# Create a grid search object
grid_LR_class = GridSearchCV(estimator = LogisticRegression(),
                             param_grid = parameter_grid,
                             scoring='accuracy',
                             n_jobs=4,
                             cv = 5,
                             refit=True,
                             return_train_score=True)

# Fit the object to our data
grid_LR_class.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(), n_jobs=4,
             param_grid={'C': [0.1, 1, 2, 3],
                         'max_iter': [3000, 4000, 5000, 6000],
                         'penalty': ['l2']},
             return_train_score=True, scoring='accuracy')

In [45]:
# print best parameter after tuning
print(grid_LR_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid_LR_class.best_estimator_)

{'C': 1, 'max_iter': 3000, 'penalty': 'l2'}
LogisticRegression(C=1, max_iter=3000)


In [46]:
# Predicted test outputs
grid_LR_class_predictions = grid_LR_class.predict(x_test)

#print Confusion Matrix
print(confusion_matrix(y_test, grid_LR_class_predictions))
 
# print Classification Report
print(classification_report(y_test, grid_LR_class_predictions))

[[164   2   0   3  32   8   1]
 [  1 171  10   8  11   8   1]
 [  0   1 196   6   1   6   0]
 [  3   6   4 166  15  14   2]
 [ 31  11   1  10 145   6   6]
 [  5  10   8  15   5 142  25]
 [  3   0   0   1   3  26 177]]
              precision    recall  f1-score   support

           1       0.79      0.78      0.79       210
           2       0.85      0.81      0.83       210
           3       0.89      0.93      0.91       210
           4       0.79      0.79      0.79       210
           5       0.68      0.69      0.69       210
           6       0.68      0.68      0.68       210
           7       0.83      0.84      0.84       210

    accuracy                           0.79      1470
   macro avg       0.79      0.79      0.79      1470
weighted avg       0.79      0.79      0.79      1470



In [47]:
# Examining results using pandas df
grid_cv_results_df = pd.DataFrame(grid_LR_class.cv_results_)
pd.set_option('display.max_columns', None)
grid_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        3.857498      0.624945         0.024799        0.005936     0.1   
1        3.527699      0.671671         0.015283        0.001265     0.1   
2        3.391776      0.509967         0.024361        0.007268     0.1   
3        3.535276      0.545039         0.024662        0.006316     0.1   
4        8.407930      1.126660         0.024484        0.006408       1   
5        8.710756      1.192086         0.025203        0.007409       1   
6        8.732003      1.165581         0.029294        0.002741       1   
7        8.925185      1.234760         0.024452        0.007142       1   
8       10.198239      1.457679         0.015704        0.000165       2   
9       10.130291      1.274789         0.020185        0.006545       2   
10       9.971844      1.413976         0.021833        0.007611       2   
11      10.156397      1.479471         0.016799        0.001491       2   
12      10.666563      0.484263         0.017351        0.002211       3   
13       9.970723      0.413251         0.021875        0.007655       3   
14       9.898076      0.417181         0.018225        0.006586       3   
15       8.920764      1.545712         0.013300        0.006829       3   

   param_max_iter param_penalty  \
0            3000            l2   
1            4000            l2   
2            5000            l2   
3            6000            l2   
4            3000            l2   
5            4000            l2   
6            5000            l2   
7            6000            l2   
8            3000            l2   
9            4000            l2   
10           5000            l2   
11           6000            l2   
12           3000            l2   
13           4000            l2   
14           5000            l2   
15           6000            l2   

                                           params  split0_test_score  \
0   {'C': 0.1, 'max_iter': 3000, 'penalty': 'l2'}           0.782799   
1   {'C': 0.1, 'max_iter': 4000, 'penalty': 'l2'}           0.782799   
2   {'C': 0.1, 'max_iter': 5000, 'penalty': 'l2'}           0.782799   
3   {'C': 0.1, 'max_iter': 6000, 'penalty': 'l2'}           0.782799   
4     {'C': 1, 'max_iter': 3000, 'penalty': 'l2'}           0.775510   
5     {'C': 1, 'max_iter': 4000, 'penalty': 'l2'}           0.775510   
6     {'C': 1, 'max_iter': 5000, 'penalty': 'l2'}           0.775510   
7     {'C': 1, 'max_iter': 6000, 'penalty': 'l2'}           0.775510   
8     {'C': 2, 'max_iter': 3000, 'penalty': 'l2'}           0.769679   
9     {'C': 2, 'max_iter': 4000, 'penalty': 'l2'}           0.769679   
10    {'C': 2, 'max_iter': 5000, 'penalty': 'l2'}           0.769679   
11    {'C': 2, 'max_iter': 6000, 'penalty': 'l2'}           0.769679   
12    {'C': 3, 'max_iter': 3000, 'penalty': 'l2'}           0.765306   
13    {'C': 3, 'max_iter': 4000, 'penalty': 'l2'}           0.765306   
14    {'C': 3, 'max_iter': 5000, 'penalty': 'l2'}           0.765306   
15    {'C': 3, 'max_iter': 6000, 'penalty': 'l2'}           0.765306   

    split1_test_score  split2_test_score  split3_test_score  \
0            0.763848           0.779883           0.763848   
1            0.763848           0.779883           0.763848   
2            0.763848           0.779883           0.763848   
3            0.763848           0.779883           0.763848   
4            0.768222           0.787172           0.776968   
5            0.768222           0.787172           0.776968   
6            0.768222           0.787172           0.776968   
7            0.768222           0.787172           0.776968   
8            0.765306           0.775510           0.771137   
9            0.765306           0.775510           0.771137   
10           0.765306           0.775510           0.771137   
11           0.765306           0.775510           0.771137   
12           0.766764           0.762391           0.762391   
13      

### Hyperparameter Tuning for Normalized Data for SVM

In [3]:
# Random Search CV

# Set up the sample space
c_list = [0.1, 1, 10, 100, 1000]
gamma_list = ['scale', 1, 0.1, 0.01, 0.001, 0.0001]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}
# Define how many samples
number_models = 10
# Create a random search object
random_SVM_class = RandomizedSearchCV(estimator = svm.SVC(),
                                      param_distributions = parameter_grid,
                                      n_iter = number_models,
                                      scoring='accuracy',
                                      n_jobs=4,
                                      cv = 10,
                                      refit=True,
                                      return_train_score = True)
# Fit the object to our data
random_SVM_class.fit(nscaled_data_train, y_train)

RandomizedSearchCV(cv=10, estimator=SVC(), n_jobs=4,
                   param_distributions={'C': [0.1, 1, 10, 100, 1000],
                                        'gamma': ['scale', 1, 0.1, 0.01, 0.001,
                                                  0.0001],
                                        'kernel': ['poly', 'rbf']},
                   return_train_score=True, scoring='accuracy')

In [4]:
# print best parameter after tuning
print(random_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(random_SVM_class.best_estimator_)

{'kernel': 'rbf', 'gamma': 1, 'C': 10}
SVC(C=10, gamma=1)


In [5]:
# Predicted test outputs
random_SVM_class_predictions = random_SVM_class.predict(nscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test,random_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, random_SVM_class_predictions))

[[168   1   0   1  30  10   0]
 [  1 179   9   6  10   4   1]
 [  0   1 196   7   2   4   0]
 [  3   5   4 170  15  11   2]
 [ 28   6   1   8 160   2   5]
 [  6   9   6  14   4 149  22]
 [  2   0   0   1   3  18 186]]
              precision    recall  f1-score   support

           1       0.81      0.80      0.80       210
           2       0.89      0.85      0.87       210
           3       0.91      0.93      0.92       210
           4       0.82      0.81      0.82       210
           5       0.71      0.76      0.74       210
           6       0.75      0.71      0.73       210
           7       0.86      0.89      0.87       210

    accuracy                           0.82      1470
   macro avg       0.82      0.82      0.82      1470
weighted avg       0.82      0.82      0.82      1470



In [6]:
# Examining results using pandas df
rand_cv_results_df = pd.DataFrame(random_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
rand_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0      10.564750      0.429175         0.920068        0.138292         poly   
1       6.787252      0.280121         0.854823        0.056746          rbf   
2      19.358951      0.730882         1.195744        0.084298         poly   
3      19.997442      1.245283         1.227007        0.138532         poly   
4       9.270921      0.859260         1.003391        0.039062          rbf   
5       4.626789      0.433491         0.981281        0.084837          rbf   
6       7.120452      0.835517         0.858977        0.075204         poly   
7       6.988788      0.500594         0.877948        0.083392         poly   
8       4.987109      0.442797         0.997592        0.127752          rbf   
9       4.444266      0.379311         0.902272        0.057827          rbf   

  param_gamma param_C                                         params  \
0           1     0.1       {'kernel': 'poly', 'gamma': 1, 'C': 0.1}   
1       scale       1    {'kernel': 'rbf', 'gamma': 'scale', 'C': 1}   
2         0.1      10      {'kernel': 'poly', 'gamma': 0.1, 'C': 10}   
3      0.0001      10   {'kernel': 'poly', 'gamma': 0.0001, 'C': 10}   
4      0.0001    1000  {'kernel': 'rbf', 'gamma': 0.0001, 'C': 1000}   
5         0.1      10       {'kernel': 'rbf', 'gamma': 0.1, 'C': 10}   
6       scale       1   {'kernel': 'poly', 'gamma': 'scale', 'C': 1}   
7           1       1         {'kernel': 'poly', 'gamma': 1, 'C': 1}   
8           1      10         {'kernel': 'rbf', 'gamma': 1, 'C': 10}   
9           1     100        {'kernel': 'rbf', 'gamma': 1, 'C': 100}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.679300           0.696793           0.699708           0.679300   
1           0.781341           0.781341           0.743440           0.790087   
2           0.533528           0.597668           0.542274           0.533528   
3           0.533528           0.586006           0.539359           0.527697   
4           0.688047           0.714286           0.702624           0.708455   
5           0.769679           0.787172           0.746356           0.769679   
6           0.793003           0.790087           0.746356           0.781341   
7           0.793003           0.790087           0.746356           0.781341   
8           0.793003           0.784257           0.752187           0.798834   
9           0.781341           0.784257           0.749271           0.790087   

   split4_test_score  split5_test_score  split6_test_score  split7_test_score  \
0           0.670554           0.688047           0.661808           0.711370   
1           0.766764           0.787172           0.746356           0.790087   
2           0.542274           0.556851           0.530612           0.559767   
3           0.530612           0.556851           0.527697           0.551020   
4           0.682216           0.702624           0.682216           0.708455   
5           0.781341           0.775510           0.746356           0.793003   
6           0.775510           0.769679           0.746356           0.798834   
7           0.775510           0.769679           0.746356           0.798834   
8           0.790087           0.804665           0.743440           0.798834   
9           0.778426           0.790087           0.746356           0.801749   

   split8_test_score  split9_test_score  mean_test_score  std_test_score  \
0           0.664723           0.705539         0.685714        0.016430   
1           0.731778           0.763848         0.768222        0.020251   
2           0.545190           0.591837         0.553353        0.022613   
3           0.533528           0.574344         0.546064        0.019516   
4           0.658892           0.696793         0.694461        0.015905   
5           0.737609           0.752187         0.765889        0.018163   
6           0

In [7]:
# Grid Search CV

# Set up the sample space
c_list = [1, 2, 3, 5, 10, 100]
gamma_list = ['auto', 'scale', 1, 0.1]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}

# Create a grid search object
grid_SVM_class = GridSearchCV(estimator = svm.SVC(),
                             param_grid = parameter_grid,
                             scoring='accuracy',
                             n_jobs=4,
                             cv = 5,
                             refit=True,
                             return_train_score=True)

# Fit the object to our data
grid_SVM_class.fit(nscaled_data_train, y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=4,
             param_grid={'C': [1, 2, 3, 5, 10, 100],
                         'gamma': ['auto', 'scale', 1, 0.1],
                         'kernel': ['poly', 'rbf']},
             return_train_score=True, scoring='accuracy')

In [8]:
# print best parameter after tuning
print(grid_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid_SVM_class.best_estimator_)

{'C': 3, 'gamma': 'scale', 'kernel': 'rbf'}
SVC(C=3)


In [9]:
# Predicted test outputs
grid_SVM_class_predictions = grid_SVM_class.predict(nscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test, grid_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, grid_SVM_class_predictions))

[[161   2   0   2  32  12   1]
 [  1 172  12   5  12   7   1]
 [  0   3 196   4   2   5   0]
 [  4   5   4 162  18  15   2]
 [ 20   9   1   9 163   2   6]
 [  7   8   6  12   3 139  35]
 [  0   0   0   0   2  15 193]]
              precision    recall  f1-score   support

           1       0.83      0.77      0.80       210
           2       0.86      0.82      0.84       210
           3       0.89      0.93      0.91       210
           4       0.84      0.77      0.80       210
           5       0.70      0.78      0.74       210
           6       0.71      0.66      0.69       210
           7       0.81      0.92      0.86       210

    accuracy                           0.81      1470
   macro avg       0.81      0.81      0.81      1470
weighted avg       0.81      0.81      0.81      1470



In [10]:
# Examining results using pandas df
grid_cv_results_df = pd.DataFrame(grid_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
grid_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       15.543667      0.621895         2.177389        0.081281       1   
1       14.536932      1.011101         2.367405        0.176674       1   
2        4.659146      1.063285         1.290153        0.327358       1   
3        4.024781      0.370648         1.695156        0.136221       1   
4        4.269115      0.659489         1.167223        0.141817       1   
5        4.389405      0.738750         1.786376        0.120123       1   
6       12.169989      1.359943         1.831526        0.154531       1   
7        6.779944      1.025799         2.133436        0.209361       1   
8       12.738895      1.916288         1.963908        0.322163       2   
9       11.689229      2.074986         2.399812        0.025453       2   
10       3.890579      0.316489         1.108438        0.125514       2   
11       4.052477      0.547038         1.712210        0.152387       2   
12       4.093226      0.527090         1.104656        0.093552       2   
13       4.095638      0.693719         1.722722        0.094494       2   
14      13.712039      1.362920         1.945431        0.142086       2   
15       6.308763      1.361200         2.109221        0.172248       2   
16      12.502598      1.460676         1.917311        0.069205       3   
17      10.725888      1.706550         2.277649        0.074208       3   
18       3.492180      0.113482         1.049981        0.098443       3   
19       3.614035      0.508407         1.527687        0.063001       3   
20       3.808438      0.426072         1.118602        0.122187       3   
21       3.942664      0.513006         1.622839        0.127927       3   
22      13.264478      1.548885         2.007224        0.322931       3   
23       5.427282      0.710400         2.073027        0.061866       3   
24      12.599449      1.131476         1.919074        0.204687       5   
25      11.247491      1.487072         2.451229        0.172075       5   
26       4.129369      0.181671         1.106713        0.068456       5   
27       4.286625      0.429313         1.767102        0.123986       5   
28       4.690385      0.423237         1.280486        0.060950       5   
29       4.222307      0.715022         1.801421        0.135998       5   
30      16.840104      2.893000         2.603586        0.086787       5   
31       6.996642      0.913812         3.279045        0.181251       5   
32      17.338560      0.891988         2.584396        0.189440      10   
33      15.861993      1.736990         4.170814        0.336330      10   
34       6.540516      0.407609         1.709247        0.142972      10   
35       7.092915      1.644952         2.868370        0.216414      10   
36       7.514133      1.044782         1.640746        0.092823      10   
37       5.655285      0.635660         3.443386        1.444890      10   
38      17.026755      1.174908         2.471617        0.176893      10   
39       6.237894      0.740973         2.932258        0.191341      10   
40      18.061854      1.417951         2.511907        0.162207     100   
41       9.619221      0.852917         3.655777        0.170537     100   
42       5.879140      0.478838         1.558595        0.084327     100   
43       5.361145      0.527950         2.663409        0.126446     100   
44       7.077075      1.737558         2.076401        0.859800     100   
45       6.295857      0.523326         2.756463        0.292556     100   
46      12.770377      1.574805         2.085202        0.164739     100   
47       4.278379      0.664487         2.215121        0.248224     100   

   param_gamma param_kernel                                          params  \
0         auto         poly     {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
1         auto          rbf      {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
2        scale         poly    {'C': 1, 'g

### Hyperparameter Tuning for Standardized Data for SVM

In [11]:
# Random Search CV

# Set up the sample space
c_list = [0.1, 1, 10, 100, 1000]
gamma_list = ['scale', 1, 0.1, 0.01, 0.001, 0.0001]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}
# Define how many samples
number_models = 10
# Create a random search object
random_SVM_class = RandomizedSearchCV(estimator = svm.SVC(),
                                      param_distributions = parameter_grid,
                                      n_iter = number_models,
                                      scoring='accuracy',
                                      n_jobs=4,
                                      cv = 5,
                                      refit=True,
                                      return_train_score = True)
# Fit the object to our data
random_SVM_class.fit(sscaled_data_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_jobs=4,
                   param_distributions={'C': [0.1, 1, 10, 100, 1000],
                                        'gamma': ['scale', 1, 0.1, 0.01, 0.001,
                                                  0.0001],
                                        'kernel': ['poly', 'rbf']},
                   return_train_score=True, scoring='accuracy')

In [12]:
# print best parameter after tuning
print(random_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(random_SVM_class.best_estimator_)

{'kernel': 'rbf', 'gamma': 'scale', 'C': 100}
SVC(C=100)


In [13]:
# Predicted test outputs
random_SVM_class_predictions = random_SVM_class.predict(sscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test,random_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, random_SVM_class_predictions))

[[170   1   0   0  27  12   0]
 [  0 178   8   3  10  10   1]
 [  0   4 194   5   2   4   1]
 [  3   6   3 167  13  16   2]
 [ 26   8   1  13 151   6   5]
 [  6   6   6  13   2 153  24]
 [  0   0   0   1   3  16 190]]
              precision    recall  f1-score   support

           1       0.83      0.81      0.82       210
           2       0.88      0.85      0.86       210
           3       0.92      0.92      0.92       210
           4       0.83      0.80      0.81       210
           5       0.73      0.72      0.72       210
           6       0.71      0.73      0.72       210
           7       0.85      0.90      0.88       210

    accuracy                           0.82      1470
   macro avg       0.82      0.82      0.82      1470
weighted avg       0.82      0.82      0.82      1470



In [14]:
# Examining results using pandas df
rand_cv_results_df = pd.DataFrame(random_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
rand_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       8.984045      0.157191         2.746304        0.169100          rbf   
1       9.473170      0.582760         3.036204        0.228684          rbf   
2      12.488123      0.332491         1.693061        0.055337         poly   
3       5.107132      0.280398         2.376176        0.107138          rbf   
4       4.970643      0.102410         2.261271        0.181722          rbf   
5      14.512515      1.482628         3.456601        0.346236          rbf   
6      14.049026      0.520385         2.186122        0.066593         poly   
7      13.175904      0.227657         1.917379        0.041451         poly   
8      16.429651      1.943494         5.003713        1.793466          rbf   
9      11.281908      0.865170         1.722487        0.196814         poly   

  param_gamma param_C                                          params  \
0       0.001    1000    {'kernel': 'rbf', 'gamma': 0.001, 'C': 1000}   
1       scale     100   {'kernel': 'rbf', 'gamma': 'scale', 'C': 100}   
2         0.1    1000     {'kernel': 'poly', 'gamma': 0.1, 'C': 1000}   
3      0.0001     100    {'kernel': 'rbf', 'gamma': 0.0001, 'C': 100}   
4      0.0001    1000   {'kernel': 'rbf', 'gamma': 0.0001, 'C': 1000}   
5         0.1       1         {'kernel': 'rbf', 'gamma': 0.1, 'C': 1}   
6       scale     0.1  {'kernel': 'poly', 'gamma': 'scale', 'C': 0.1}   
7        0.01     0.1     {'kernel': 'poly', 'gamma': 0.01, 'C': 0.1}   
8        0.01       1        {'kernel': 'rbf', 'gamma': 0.01, 'C': 1}   
9        0.01    1000    {'kernel': 'poly', 'gamma': 0.01, 'C': 1000}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.782799           0.769679           0.779883           0.749271   
1           0.787172           0.765306           0.774052           0.752187   
2           0.785714           0.753644           0.752187           0.744898   
3           0.766764           0.752187           0.765306           0.752187   
4           0.746356           0.755102           0.759475           0.743440   
5           0.319242           0.300292           0.301749           0.304665   
6           0.593294           0.516035           0.546647           0.556851   
7           0.785714           0.753644           0.752187           0.744898   
8           0.518950           0.524781           0.534985           0.546647   
9           0.785714           0.753644           0.752187           0.744898   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  \
0           0.775510         0.771429        0.011928                2   
1           0.782799         0.772303        0.012553                1   
2           0.759475         0.759184        0.014055                3   
3           0.756560         0.758601        0.006294                6   
4           0.744898         0.749854        0.006294                7   
5           0.330904         0.311370        0.011864               10   
6           0.540816         0.550729        0.025171                8   
7           0.759475         0.759184        0.014055                3   
8           0.507289         0.526531        0.013468                9   
9           0.759475         0.759184        0.014055                3   

   split0_train_score  split1_train_score  split2_train_score  \
0            0.997449            0.997085            0.998178   
1            0.997449            0.997085            0.998178   
2            0.997449            0.997085            0.998178   
3            0.990160            0.990160            0.992711   
4            0.997449            0.997085            0.998178   
5            0.997449            0.997085            0.998178   
6            0.656341            0.620627            0.631560   
7            0.997449            0.997085            0.998178   
8            0.997449     

In [15]:
# Grid Search CV

# Set up the sample space
c_list = [1, 3, 100, 1000]
gamma_list = ['auto', 'scale', 1, 0.1]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}

# Create a grid search object
grid_SVM_class = GridSearchCV(estimator = svm.SVC(),
                             param_grid = parameter_grid,
                             scoring='accuracy',
                             n_jobs=4,
                             cv = 5,
                             refit=True,
                             return_train_score=True)

# Fit the object to our data
grid_SVM_class.fit(sscaled_data_train, y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=4,
             param_grid={'C': [1, 3, 100, 1000],
                         'gamma': ['auto', 'scale', 1, 0.1],
                         'kernel': ['poly', 'rbf']},
             return_train_score=True, scoring='accuracy')

In [16]:
# print best parameter after tuning
print(grid_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid_SVM_class.best_estimator_)

{'C': 3, 'gamma': 'auto', 'kernel': 'rbf'}
SVC(C=3, gamma='auto')


In [17]:
# Predicted test outputs
grid_SVM_class_predictions = grid_SVM_class.predict(sscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test, grid_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, grid_SVM_class_predictions))

[[173   1   0   1  23  12   0]
 [  0 174   8   3  12  12   1]
 [  0   5 194   4   2   4   1]
 [  4   5   4 166  13  16   2]
 [ 26   7   1  12 153   6   5]
 [  6   7   6  11   4 152  24]
 [  0   0   0   0   1  17 192]]
              precision    recall  f1-score   support

           1       0.83      0.82      0.83       210
           2       0.87      0.83      0.85       210
           3       0.91      0.92      0.92       210
           4       0.84      0.79      0.82       210
           5       0.74      0.73      0.73       210
           6       0.69      0.72      0.71       210
           7       0.85      0.91      0.88       210

    accuracy                           0.82      1470
   macro avg       0.82      0.82      0.82      1470
weighted avg       0.82      0.82      0.82      1470



In [18]:
# Examining results using pandas df
grid_cv_results_df = pd.DataFrame(grid_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
grid_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       11.658449      0.108038         1.892718        0.125339       1   
1        8.400100      1.228252         3.057011        0.064939       1   
2       10.347663      0.298369         1.823860        0.164511       1   
3        7.207869      0.854767         2.847299        0.138356       1   
4       12.003970      0.172240         1.880228        0.050515       1   
5       16.603175      1.309576         3.788525        0.353424       1   
6       11.101491      0.323399         1.749464        0.066031       1   
7       15.436338      0.612048         3.543386        0.102824       1   
8       11.280744      0.458843         1.787863        0.061535       3   
9        7.556130      0.656163         2.987109        0.058215       3   
10      10.997504      0.939115         1.856058        0.071766       3   
11       7.851416      0.732801         2.921844        0.184967       3   
12      11.472378      0.529616         1.770749        0.052057       3   
13      16.083726      0.956835         3.666482        0.229540       3   
14      11.196744      0.627248         1.783625        0.058730       3   
15      15.157626      1.477640         3.465744        0.192128       3   
16      11.562079      0.306858         1.810180        0.084121     100   
17       8.196736      0.807967         2.937078        0.165249     100   
18      11.535865      0.546326         1.813854        0.068562     100   
19       8.333875      0.783352         3.073904        0.130039     100   
20      11.527103      0.815182         1.825082        0.122687     100   
21      17.226564      0.740268         3.665056        0.273945     100   
22      11.508326      0.446666         1.778657        0.040777     100   
23      14.140247      1.256025         3.307917        0.140322     100   
24      11.546573      0.524030         1.750727        0.063994    1000   
25       8.254653      0.826577         3.051657        0.218065    1000   
26      11.607971      1.081131         1.820486        0.086767    1000   
27       8.185153      0.827407         3.027694        0.148235    1000   
28      12.060476      0.806620         1.909938        0.188057    1000   
29      16.355868      1.983808         3.672748        0.130550    1000   
30      11.273324      0.748625         1.765496        0.094487    1000   
31      13.791784      2.450806         3.319234        0.360653    1000   

   param_gamma param_kernel                                           params  \
0         auto         poly      {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
1         auto          rbf       {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
2        scale         poly     {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}   
3        scale          rbf      {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}   
4            1         poly           {'C': 1, 'gamma': 1, 'kernel': 'poly'}   
5            1          rbf            {'C': 1, 'gamma': 1, 'kernel': 'rbf'}   
6          0.1         poly         {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}   
7          0.1          rbf          {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}   
8         auto         poly      {'C': 3, 'gamma': 'auto', 'kernel': 'poly'}   
9         auto          rbf       {'C': 3, 'gamma': 'auto', 'kernel': 'rbf'}   
10       scale         poly     {'C': 3, 'gamma': 'scale', 'kernel': 'poly'}   
11       scale          rbf      {'C': 3, 'gamma': 'scale', 'kernel': 'rbf'}   
12           1         poly           {'C': 3, 'gamma': 1, 'kernel': 'poly'}   
13           1          rbf            {'C': 3, 'gamma': 1, 'kernel': 'rbf'}   
14         0.1         poly         {'C': 3, 'gamma': 0.1, 'kernel': 'poly'}   
15         0.1          rbf          {'C': 3, 'gamma': 0.1, 'kernel': 'rbf'}   
16        auto         poly    {'C': 100, 'gamma': 'auto', 'kernel': 'poly'}   
17        auto          rbf     {'C': 100, 'gamma': 'au

## FineTuned GPT Hinglish

In [19]:
# Fine Tuned GPT Hinglish vectorized data
x_df = pd.read_csv(pwd+"//Datasets//Kabita//FineTunedTransformers//gpt_hinglish_finetuned_vectorized_kabita_dataset.csv")
y_df = labels_df['kabita_labels']
# Test train split
x_train,x_test,y_train,y_test = train_test_split(x_df, y_df, test_size=0.30,random_state=21,stratify=y_df)

# Standard scaling of train data
standard_model = StandardScaler()
sscaled_data_train = standard_model.fit_transform(x_train)
# Standard scaling of test data
sscaled_data_test = standard_model.fit_transform(x_test)

### Hyperparameter Tuning for Standardized Data for SVM

In [20]:
# Random Search CV

# Set up the sample space
c_list = [0.1, 1, 10, 100, 1000]
gamma_list = ['scale', 1, 0.1, 0.01, 0.001, 0.0001]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}
# Define how many samples
number_models = 10
# Create a random search object
random_SVM_class = RandomizedSearchCV(estimator = svm.SVC(),
                                      param_distributions = parameter_grid,
                                      n_iter = number_models,
                                      scoring='accuracy',
                                      n_jobs=4,
                                      cv = 5,
                                      refit=True,
                                      return_train_score = True)
# Fit the object to our data
random_SVM_class.fit(sscaled_data_train, y_train)

RandomizedSearchCV(cv=5, estimator=SVC(), n_jobs=4,
                   param_distributions={'C': [0.1, 1, 10, 100, 1000],
                                        'gamma': ['scale', 1, 0.1, 0.01, 0.001,
                                                  0.0001],
                                        'kernel': ['poly', 'rbf']},
                   return_train_score=True, scoring='accuracy')

In [21]:
# print best parameter after tuning
print(random_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(random_SVM_class.best_estimator_)

{'kernel': 'rbf', 'gamma': 0.0001, 'C': 10}
SVC(C=10, gamma=0.0001)


In [22]:
# Predicted test outputs
random_SVM_class_predictions = random_SVM_class.predict(sscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test,random_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, random_SVM_class_predictions))

[[160   0   0   2  33  11   4]
 [  0 182   6   9   8   3   2]
 [  1   2 196   5   1   5   0]
 [  4   6   2 170  11  14   3]
 [ 25   9   3  14 146   5   8]
 [  3   4   3  17   5 129  49]
 [  0   1   0   1   3  16 189]]
              precision    recall  f1-score   support

           1       0.83      0.76      0.79       210
           2       0.89      0.87      0.88       210
           3       0.93      0.93      0.93       210
           4       0.78      0.81      0.79       210
           5       0.71      0.70      0.70       210
           6       0.70      0.61      0.66       210
           7       0.74      0.90      0.81       210

    accuracy                           0.80      1470
   macro avg       0.80      0.80      0.80      1470
weighted avg       0.80      0.80      0.80      1470



In [23]:
# Examining results using pandas df
rand_cv_results_df = pd.DataFrame(random_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
rand_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0      18.247943      0.331747         2.554531        0.071171         poly   
1      20.661357      2.217096         4.895210        0.096823          rbf   
2      16.817933      0.208361         2.393858        0.085665         poly   
3      17.893028      0.149215         2.537200        0.100656         poly   
4      17.681365      0.272679         2.502431        0.047001         poly   
5      18.728064      0.198735         2.891419        0.057035         poly   
6      17.708750      0.138746         2.519612        0.060702         poly   
7       6.673207      0.657424         3.461624        0.198658          rbf   
8      20.505315      0.461576         4.849858        0.187321          rbf   
9      11.695765      0.506702         3.595111        0.443995          rbf   

  param_gamma param_C                                           params  \
0        0.01       1        {'kernel': 'poly', 'gamma': 0.01, 'C': 1}   
1        0.01       1         {'kernel': 'rbf', 'gamma': 0.01, 'C': 1}   
2       scale    1000  {'kernel': 'poly', 'gamma': 'scale', 'C': 1000}   
3         0.1     0.1       {'kernel': 'poly', 'gamma': 0.1, 'C': 0.1}   
4         0.1       1         {'kernel': 'poly', 'gamma': 0.1, 'C': 1}   
5      0.0001     100    {'kernel': 'poly', 'gamma': 0.0001, 'C': 100}   
6        0.01      10       {'kernel': 'poly', 'gamma': 0.01, 'C': 10}   
7      0.0001      10      {'kernel': 'rbf', 'gamma': 0.0001, 'C': 10}   
8           1       1            {'kernel': 'rbf', 'gamma': 1, 'C': 1}   
9       scale     100    {'kernel': 'rbf', 'gamma': 'scale', 'C': 100}   

   split0_test_score  split1_test_score  split2_test_score  split3_test_score  \
0           0.739067           0.749271           0.752187           0.741983   
1           0.409621           0.431487           0.432945           0.405248   
2           0.739067           0.749271           0.752187           0.741983   
3           0.739067           0.749271           0.752187           0.741983   
4           0.739067           0.749271           0.752187           0.741983   
5           0.488338           0.469388           0.479592           0.505831   
6           0.739067           0.749271           0.752187           0.741983   
7           0.769679           0.795918           0.787172           0.788630   
8           0.393586           0.383382           0.379009           0.374636   
9           0.775510           0.794461           0.793003           0.787172   

   split4_test_score  mean_test_score  std_test_score  rank_test_score  \
0           0.740525         0.744606        0.005166                3   
1           0.428571         0.421574        0.011713                9   
2           0.740525         0.744606        0.005166                3   
3           0.740525         0.744606        0.005166                3   
4           0.740525         0.744606        0.005166                3   
5           0.488338         0.486297        0.012007                8   
6           0.740525         0.744606        0.005166                3   
7           0.793003         0.786880        0.009145                1   
8           0.393586         0.384840        0.007658               10   
9           0.782799         0.786589        0.006936                2   

   split0_train_score  split1_train_score  split2_train_score  \
0            0.997449            0.997085            0.998178   
1            0.997449            0.997085            0.998178   
2            0.997449            0.997085            0.998178   
3            0.997449            0.997085            0.998178   
4            0.997449            0.997085            0.998178   
5            0.552478            0.565598            0.570335   
6            0.997449            0.997085            0.998178   
7            0.926385            0.916181            0.918003   
8            0.

In [24]:
# Grid Search CV

# Set up the sample space
c_list = [1, 10, 100, 1000]
gamma_list = ['auto', 'scale', 0.0001, 0.1]
kernel_list = ['poly','rbf']
# Create the grid
parameter_grid = {'C' : c_list, 'gamma' : gamma_list, 'kernel' : kernel_list}

# Create a grid search object
grid_SVM_class = GridSearchCV(estimator = svm.SVC(),
                             param_grid = parameter_grid,
                             scoring='accuracy',
                             n_jobs=6,
                             cv = 5,
                             refit=True,
                             return_train_score=True)

# Fit the object to our data
grid_SVM_class.fit(sscaled_data_train, y_train)

GridSearchCV(cv=5, estimator=SVC(), n_jobs=6,
             param_grid={'C': [1, 10, 100, 1000],
                         'gamma': ['auto', 'scale', 0.0001, 0.1],
                         'kernel': ['poly', 'rbf']},
             return_train_score=True, scoring='accuracy')

In [25]:
# print best parameter after tuning
print(grid_SVM_class.best_params_)
 
# print how our model looks after hyper-parameter tuning
print(grid_SVM_class.best_estimator_)

{'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}
SVC(C=10, gamma='auto')


In [26]:
# Predicted test outputs
grid_SVM_class_predictions = grid_SVM_class.predict(sscaled_data_test)

#print Confusion Matrix
print(confusion_matrix(y_test, grid_SVM_class_predictions))
 
# print Classification Report
print(classification_report(y_test, grid_SVM_class_predictions))

[[161   0   0   2  35  11   1]
 [  1 182   5   7   9   6   0]
 [  1   1 196   5   4   3   0]
 [  3   8   5 172   9  12   1]
 [ 23   4   3  16 155   3   6]
 [  3   7   4  12   5 143  36]
 [  1   1   0   0   3  23 182]]
              precision    recall  f1-score   support

           1       0.83      0.77      0.80       210
           2       0.90      0.87      0.88       210
           3       0.92      0.93      0.93       210
           4       0.80      0.82      0.81       210
           5       0.70      0.74      0.72       210
           6       0.71      0.68      0.70       210
           7       0.81      0.87      0.83       210

    accuracy                           0.81      1470
   macro avg       0.81      0.81      0.81      1470
weighted avg       0.81      0.81      0.81      1470



In [27]:
# Examining results using pandas df
grid_cv_results_df = pd.DataFrame(grid_SVM_class.cv_results_)
pd.set_option('display.max_columns', None)
grid_cv_results_df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       20.825841      0.056213         3.384423        0.043852       1   
1       15.525270      0.109069         4.828736        0.324756       1   
2       19.359136      0.785114         2.983197        0.260425       1   
3       14.982529      0.987448         5.118737        0.213796       1   
4       29.441437      1.015042         4.093700        0.170232       1   
5       15.535385      0.737784         5.060856        0.372666       1   
6       23.016553      2.003271         3.314668        0.038642       1   
7       27.551253      1.446582         5.809424        0.305563       1   
8       21.789089      1.516345         3.142183        0.201943      10   
9       17.331294      1.291662         5.059342        0.205656      10   
10      21.917739      1.234384         3.133098        0.148004      10   
11      17.447002      1.044381         4.826743        0.381388      10   
12      27.474829      1.937524         4.051076        0.156538      10   
13       9.984042      0.310920         4.290919        0.257913      10   
14      22.646640      1.906035         3.213909        0.193176      10   
15      26.793621      1.496196         5.472004        0.392386      10   
16      21.787564      1.476958         3.101645        0.235930     100   
17      17.189665      1.293564         5.011213        0.264865     100   
18      22.046313      1.613964         3.145527        0.201494     100   
19      17.346991      1.360385         4.913195        0.237460     100   
20      23.759625      1.757689         3.734587        0.164071     100   
21       8.789700      0.500499         4.212926        0.266171     100   
22      22.763097      1.394122         3.327162        0.163844     100   
23      26.859875      1.350503         5.747122        0.504584     100   
24      23.161605      1.560567         3.218368        0.153336    1000   
25      17.268051      1.349289         5.052385        0.296868    1000   
26      22.032445      1.436765         3.086309        0.178950    1000   
27      17.497811      1.367034         4.956587        0.193006    1000   
28      18.653879      1.423248         3.215198        0.173537    1000   
29       8.876933      0.739398         3.974759        0.310170    1000   
30      22.689707      1.669868         3.370853        0.051604    1000   
31      25.688041      2.754650         5.014736        0.711238    1000   

   param_gamma param_kernel                                           params  \
0         auto         poly      {'C': 1, 'gamma': 'auto', 'kernel': 'poly'}   
1         auto          rbf       {'C': 1, 'gamma': 'auto', 'kernel': 'rbf'}   
2        scale         poly     {'C': 1, 'gamma': 'scale', 'kernel': 'poly'}   
3        scale          rbf      {'C': 1, 'gamma': 'scale', 'kernel': 'rbf'}   
4       0.0001         poly      {'C': 1, 'gamma': 0.0001, 'kernel': 'poly'}   
5       0.0001          rbf       {'C': 1, 'gamma': 0.0001, 'kernel': 'rbf'}   
6          0.1         poly         {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}   
7          0.1          rbf          {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}   
8         auto         poly     {'C': 10, 'gamma': 'auto', 'kernel': 'poly'}   
9         auto          rbf      {'C': 10, 'gamma': 'auto', 'kernel': 'rbf'}   
10       scale         poly    {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}   
11       scale          rbf     {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}   
12      0.0001         poly     {'C': 10, 'gamma': 0.0001, 'kernel': 'poly'}   
13      0.0001          rbf      {'C': 10, 'gamma': 0.0001, 'kernel': 'rbf'}   
14         0.1         poly        {'C': 10, 'gamma': 0.1, 'kernel': 'poly'}   
15         0.1          rbf         {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}   
16        auto         poly    {'C': 100, 'gamma': 'auto', 'kernel': 'poly'}   
17        auto          rbf     {'C': 100, 'gamma': 'au