In [1]:
import pandas as pd
import numpy as np
import os,sys
import re
pwd = os.getcwd()

In [2]:
# reading dataset
kb_df1 = pd.read_csv(pwd+"//Datasets//Kabita//Input//kabitakitchen.csv", encoding_errors='ignore')
kb_df1

id  \
0     Ugy_CBm-_CKA3YqrzcB4AaABAg   
1     Ugy9mx9nuTWJu4dRac14AaABAg   
2     Ugz8T2MKLYucL3dM9nh4AaABAg   
3     Ugx_1cCjRbCaDgL0FLF4AaABAg   
4     UgzLhKVAJ6NN3nZXyjN4AaABAg   
...                          ...   
4895        UgjFXyC0Qhzk5ngCoAEC   
4896        UghP3bitlJuM13gCoAEC   
4897        UghztLZOqvedfXgCoAEC   
4898        UggX5Fi2Y430zXgCoAEC   
4899        UghTaB9XvOQ_MngCoAEC   

                                            commentText  Labels  
0                               Pudina ptta nhi dalu to       7  
1                         Chiken kacha tu ni rhy ga sis       7  
2     Hello mam, I love your all recipes.... 😋😋😋\nAl...       4  
3     Its awesome recipe plzz make handi chicken in ...       2  
4     Yeh jo measurement hai.........kitne logon ke ...       7  
...                                                 ...     ...  
4895  i love chole...thank you kabitaji for sharing ...       1  
4896                                        thnakyou mm       1  
4897                                         thanks mam       1  
4898                                       u r fabulous       4  
4899                             thnq fr the recipe.  💜       1  

[4900 rows x 3 columns]

In [3]:
# taking first 4000 rows
kb_df = kb_df1.head(4000)
kb_df

id  \
0     Ugy_CBm-_CKA3YqrzcB4AaABAg   
1     Ugy9mx9nuTWJu4dRac14AaABAg   
2     Ugz8T2MKLYucL3dM9nh4AaABAg   
3     Ugx_1cCjRbCaDgL0FLF4AaABAg   
4     UgzLhKVAJ6NN3nZXyjN4AaABAg   
...                          ...   
3995  Ugziuh6emJELBrAeeF94AaABAg   
3996  UgwcFoPccKX7FTf8C6p4AaABAg   
3997  UgwgNX3dnWIa3VeDNj14AaABAg   
3998  UgwKcL5tRdBq_i4a_xZ4AaABAg   
3999  Ugy9xw1FFM7qvDHbc-l4AaABAg   

                                            commentText  Labels  
0                               Pudina ptta nhi dalu to       7  
1                         Chiken kacha tu ni rhy ga sis       7  
2     Hello mam, I love your all recipes.... 😋😋😋\nAl...       4  
3     Its awesome recipe plzz make handi chicken in ...       2  
4     Yeh jo measurement hai.........kitne logon ke ...       7  
...                                                 ...     ...  
3995                   Aap ka beta bahut hi cute hai di       6  
3996  Thank you Kabita ji. Chole bohot tasty ban gay...       5  
3997  mummy ki yaad ajata hai..aap ka recepie KO dek...       6  
3998  I tried this recipe. It was very tasty. My fam...       5  
3999                                       Good cooking       4  

[4000 rows x 3 columns]

In [4]:
# taking last 900 rows for final test
kb_df_final = kb_df1.tail(900)
kb_df_final

id  \
4000  UgwTChiRIwmZ_yOM6VN4AaABAg   
4001  UgzCn71OoVpV7nDwzTh4AaABAg   
4002  UgzLTkliXsCNmI8z7Gp4AaABAg   
4003  Ugx3T0-iKYy5nXtQOZB4AaABAg   
4004  Ugz0kq_TqGNXlxfAi8B4AaABAg   
...                          ...   
4895        UgjFXyC0Qhzk5ngCoAEC   
4896        UghP3bitlJuM13gCoAEC   
4897        UghztLZOqvedfXgCoAEC   
4898        UggX5Fi2Y430zXgCoAEC   
4899        UghTaB9XvOQ_MngCoAEC   

                                            commentText  Labels  
4000  Aj mein phir sa chola bnana ja rhi ho ...Bht t...       2  
4001                                           So testy       2  
4002                                          Nice mam        3  
4003                                      Yummyyyyyyyyy       2  
4004  Mam maine aaj ye recipe pehli bar banayi bahot...       1  
...                                                 ...     ...  
4895  i love chole...thank you kabitaji for sharing ...       1  
4896                                        thnakyou mm       1  
4897                                         thanks mam       1  
4898                                       u r fabulous       4  
4899                             thnq fr the recipe.  💜       1  

[900 rows x 3 columns]

In [5]:
kb_df['Labels'] = kb_df['Labels']-1
kb_df_final['Labels'] = kb_df_final['Labels']-1

C:\Users\murth\AppData\Local\Temp/ipykernel_11308/3636796469.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kb_df['Labels'] = kb_df['Labels']-1
C:\Users\murth\AppData\Local\Temp/ipykernel_11308/3636796469.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  kb_df_final['Labels'] = kb_df_final['Labels']-1


In [6]:
X=list(kb_df['commentText'])
y=list(kb_df['Labels'])
X_final = list(kb_df_final['commentText'])
y_final=list(kb_df_final['Labels'])

In [7]:
print(len(X),len(y),len(X_final),len(y_final))

4000 4000 900 900


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 30)

In [9]:
from transformers import BertTokenizer
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

In [10]:
train_encodings = tokenizer(X_train, truncation=True, padding=True)
test_encodings = tokenizer(X_test, truncation=True, padding=True)
test_encodings_final = tokenizer(X_final, truncation=True, padding=True)

In [11]:
print(test_encodings)

{'input_ids': [[101, 1045, 2097, 3046, 2023, 2005, 2469, 1012, 4067, 2017, 10556, 16313, 2050, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 4283, 5003, 2050, 1012, 1012, 1012, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [101, 2200, 2200, 3835,

In [12]:
import tensorflow as tf

train_dataset = tf.data.Dataset.from_tensor_slices((
    dict(train_encodings),
    y_train
))

test_dataset = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings),
    y_test
))

test_dataset_final = tf.data.Dataset.from_tensor_slices((
    dict(test_encodings_final),
    y_final
))

In [13]:
print(test_dataset)

<TensorSliceDataset element_spec=({'input_ids': TensorSpec(shape=(149,), dtype=tf.int32, name=None), 'token_type_ids': TensorSpec(shape=(149,), dtype=tf.int32, name=None), 'attention_mask': TensorSpec(shape=(149,), dtype=tf.int32, name=None)}, TensorSpec(shape=(), dtype=tf.int32, name=None))>


In [14]:
from transformers import TFBertForSequenceClassification, TFTrainer, TFTrainingArguments

training_args = TFTrainingArguments(
    output_dir='./Berttrailresults',          # output directory
    num_train_epochs=2,              # total number of training epochs
    per_device_train_batch_size=8,  # batch size per device during training
    per_device_eval_batch_size=16,   # batch size for evaluation
    warmup_steps=500,                # number of warmup steps for learning rate scheduler
    weight_decay=0.01,               # strength of weight decay
    logging_dir='./Berttraillogs',           # directory for storing logs
    logging_steps=10,
    eval_steps=10
)

In [15]:
with training_args.strategy.scope():
    model = TFBertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=7)

trainer = TFTrainer(
    model=model,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=train_dataset,         # training dataset
    eval_dataset=test_dataset             # evaluation dataset
)

trainer.train()

All model checkpoint layers were used when initializing TFBertForSequenceClassification.

Some layers of TFBertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
C:\Users\murth\anaconda3\lib\site-packages\transformers\trainer_tf.py:115: FutureWarning: The class `TFTrainer` is deprecated and will be removed in version 5 of Transformers. We recommend using native Keras instead, by calling methods like `fit()` and `predict()` directly on the model object. Detailed examples of the Keras style can be found in our examples at https://github.com/huggingface/transformers/tree/main/examples/tensorflow
  warnings.warn(
wandb: Currently logged in as: murthy. Use `wandb login --relogin` to force relogin


In [16]:
trainer.evaluate(test_dataset)

{'eval_loss': 0.4837094497680664}

In [17]:
output=trainer.predict(test_dataset)

In [18]:
print(output)

PredictionOutput(predictions=array([[ 4.219732  , -0.8070803 , -2.574721  , ...,  1.5097584 ,
        -1.1149458 , -0.5545412 ],
       [ 4.2363315 , -0.8421448 , -2.5472095 , ...,  1.5419447 ,
        -1.1368772 , -0.5571414 ],
       [-2.170654  ,  1.1549878 ,  4.8570576 , ...,  0.2094058 ,
        -1.4181255 , -2.7703178 ],
       ...,
       [-2.0917475 ,  0.9347947 ,  4.9944043 , ..., -0.62595063,
        -1.1022991 , -2.0772562 ],
       [ 0.696291  , -0.47557303,  0.1319006 , ..., -0.49760044,
         2.2693799 , -1.6171224 ],
       [-1.3029655 ,  0.15686609, -0.6494523 , ..., -0.9795483 ,
         3.2789435 , -1.2170024 ]], dtype=float32), label_ids=array([0, 0, 2, 4, 3, 2, 1, 4, 6, 0, 2, 2, 5, 0, 1, 1, 6, 4, 6, 4, 6, 2,
       6, 6, 0, 0, 4, 1, 4, 4, 6, 3, 1, 1, 1, 5, 2, 3, 5, 5, 6, 4, 0, 0,
       2, 3, 4, 4, 5, 3, 6, 0, 6, 6, 0, 2, 5, 2, 1, 2, 4, 5, 2, 4, 2, 6,
       6, 5, 0, 6, 5, 5, 1, 3, 5, 0, 1, 6, 6, 6, 1, 4, 2, 6, 1, 1, 0, 2,
       3, 5, 6, 5, 0, 1, 1, 1, 4, 4, 3, 

In [19]:
output[1].shape

(800,)

In [20]:
output[0]

array([[ 4.219732  , -0.8070803 , -2.574721  , ...,  1.5097584 ,
        -1.1149458 , -0.5545412 ],
       [ 4.2363315 , -0.8421448 , -2.5472095 , ...,  1.5419447 ,
        -1.1368772 , -0.5571414 ],
       [-2.170654  ,  1.1549878 ,  4.8570576 , ...,  0.2094058 ,
        -1.4181255 , -2.7703178 ],
       ...,
       [-2.0917475 ,  0.9347947 ,  4.9944043 , ..., -0.62595063,
        -1.1022991 , -2.0772562 ],
       [ 0.696291  , -0.47557303,  0.1319006 , ..., -0.49760044,
         2.2693799 , -1.6171224 ],
       [-1.3029655 ,  0.15686609, -0.6494523 , ..., -0.9795483 ,
         3.2789435 , -1.2170024 ]], dtype=float32)

In [21]:
from sklearn.metrics import confusion_matrix

cm=confusion_matrix(y_test,output[1])
cm

array([[105,   0,   0,   0,   0,   0,   0],
       [  0, 113,   0,   0,   0,   0,   0],
       [  0,   0, 108,   0,   0,   0,   0],
       [  0,   0,   0,  97,   0,   0,   0],
       [  0,   0,   0,   0, 103,   0,   0],
       [  0,   0,   0,   0,   0, 156,   0],
       [  0,   0,   0,   0,   0,   0, 118]], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(y_test,output[1])
acc

1.0

In [23]:
from sklearn.metrics import classification_report

clr = classification_report(y_test,output[1])
print(clr)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       105
           1       1.00      1.00      1.00       113
           2       1.00      1.00      1.00       108
           3       1.00      1.00      1.00        97
           4       1.00      1.00      1.00       103
           5       1.00      1.00      1.00       156
           6       1.00      1.00      1.00       118

    accuracy                           1.00       800
   macro avg       1.00      1.00      1.00       800
weighted avg       1.00      1.00      1.00       800



### working on final data testing

In [24]:
output_final=trainer.predict(test_dataset_final)

In [25]:
print(output_final)

PredictionOutput(predictions=array([[-1.9268705 ,  3.5062196 , -1.9877858 , ...,  0.90578765,
         0.5503884 , -0.01943265],
       [-1.7495657 ,  4.6264086 , -1.0057834 , ...,  1.4181205 ,
        -0.9319315 , -1.5631785 ],
       [-1.9904951 ,  0.9444874 ,  4.987347  , ..., -0.40788838,
        -1.1698551 , -2.1531465 ],
       ...,
       [ 4.2371182 , -0.84246504, -2.5364068 , ...,  1.5701085 ,
        -1.1501578 , -0.5655556 ],
       [-0.98493844, -0.8524971 , -0.53802365, ...,  0.15835397,
        -0.29553047, -1.5154228 ],
       [ 4.1175337 , -0.8522393 , -2.4943864 , ...,  2.0001454 ,
        -1.1510618 , -0.76057714]], dtype=float32), label_ids=array([1, 1, 2, 1, 0, 0, 2, 1, 2, 3, 5, 5, 1, 3, 5, 2, 0, 5, 5, 2, 2, 3,
       2, 2, 2, 5, 0, 2, 5, 3, 0, 2, 4, 1, 4, 1, 2, 3, 5, 4, 1, 3, 2, 2,
       4, 3, 4, 3, 4, 1, 5, 4, 2, 4, 5, 5, 2, 1, 2, 3, 5, 1, 5, 1, 4, 5,
       5, 4, 5, 2, 3, 3, 4, 4, 2, 5, 4, 1, 3, 2, 1, 2, 1, 2, 4, 3, 5, 5,
       3, 3, 5, 2, 4, 3, 2, 3, 2, 2, 0, 

In [26]:
output_final[1].shape

(900,)

In [27]:
cm_final=confusion_matrix(y_final,output_final[1])
cm_final

array([[193,   0,   0,   0,   0,   0],
       [  0, 154,   0,   0,   0,   0],
       [  0,   0, 146,   0,   0,   0],
       [  0,   0,   0, 207,   0,   0],
       [  0,   0,   0,   0, 169,   0],
       [  0,   0,   0,   0,   0,  31]], dtype=int64)

In [28]:
acc_final=accuracy_score(y_final,output_final[1])
acc_final

1.0

In [29]:
clr_final = classification_report(y_final,output_final[1])
print(clr_final)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       193
           1       1.00      1.00      1.00       154
           2       1.00      1.00      1.00       146
           3       1.00      1.00      1.00       207
           4       1.00      1.00      1.00       169
           5       1.00      1.00      1.00        31

    accuracy                           1.00       900
   macro avg       1.00      1.00      1.00       900
weighted avg       1.00      1.00      1.00       900

